import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create i18n Translation",
  description: "Generated by create next app",
};
type Locale = "en" | "fr" | "es"; // Define the valid locale values
export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  },
  params: { locale: Locale }
) {
  //Get the current locale
  const { locale }: any = useLocale();
  if (params?.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
